laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('perfil', ['as' => 'perfil', 'uses' => 'PerfilController@index']);

Route::get('projetos/{categoria_slug?}', [
    'as'   => 'projetos',
    'uses' => 'ProjetosController@index'
]);
Route::get('projetos/{categoria_slug}/{projeto_slug}', [
    'as'   => 'projetos.show',
    'uses' => 'ProjetosController@show'
]);

Route::get('clipping', [
    'as'   => 'clipping',
    'uses' => 'ClippingController@index'
]);
Route::get('clipping/{projeto_slug}', [
    'as'   => 'clipping.show',
    'uses' => 'ClippingController@show'
]);

Route::get('contato', [
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
]);
Route::post('contato', [
    'as'   => 'contato.envio',
    'uses' => 'ContatoController@envio'
]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('banners', 'Painel\BannersController');

    Route::resource('perfil', 'Painel\PerfilController');

    Route::resource('projetos/categorias', 'Painel\ProjetosCategoriasController');
    Route::resource('projetos', 'Painel\ProjetosController');
    Route::resource('projetos.imagens', 'Painel\ProjetosImagensController');

    Route::resource('clipping', 'Painel\ClippingController');
    Route::resource('clipping.imagens', 'Painel\ClippingImagensController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/models/Clipping.php
<?php

class Clipping extends Eloquent
{

    protected $table = 'clipping';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('data', 'DESC')->orderBy('id', 'DESC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

    public function imagens()
    {
        return $this->hasMany('ClippingImagem', 'clipping_id')->orderBy('ordem', 'ASC');
    }

    public function setDataAttribute($date)
    {
        $this->attributes['data'] = Carbon\Carbon::createFromFormat('m/Y', $date)->format('Y-m');
    }

    public function getDataAttribute($date)
    {
        return Carbon\Carbon::createFromFormat('Y-m', $date)->format('m/Y');
    }

}

laravel/app/controllers/ClippingController.php
<?php

use \Clipping;

class ClippingController extends BaseController {

	public function index()
	{
        $clipping = Clipping::ordenados()->get();

		return $this->view('frontend.clipping.index', compact('clipping'));
	}

    public function show($slug)
    {
        $clipping = Clipping::with('imagens')->slug($slug)->first();
        if (!$clipping) App::abort('404');

        $data_clipping = Carbon\Carbon::createFromFormat('m/Y', $clipping->data)->format('Y-m');
        $anterior  = Clipping::select('slug')
                        ->where('data', '>', $data_clipping)
                        ->orWhere(function($query) use ($data_clipping, $clipping) {
                          $query->where('data', $data_clipping)
                                ->where('id', '>', $clipping->id);
                        })
                        ->orderBy('data', 'ASC')
                        ->orderBy('id', 'ASC')
                        ->first();
        $proximo = Clipping::select('slug')
                        ->where('data', '<', $data_clipping)
                        ->orWhere(function($query) use ($data_clipping, $clipping) {
                          $query->where('data', $data_clipping)
                                ->where('id', '<', $clipping->id);
                        })
                        ->orderBy('data', 'DESC')
                        ->orderBy('id', 'DESC')
                        ->first();

        return $this->view('frontend.clipping.show', compact('clipping', 'anterior', 'proximo'));
    }

}

laravel/app/controllers/painel/ClippingController.php
<?php

namespace Painel;

use \Clipping, \View, \Input, \Session, \Redirect, \Validator, \Str, \CropImage;

class ClippingController extends BasePainelController {

    private $validation_rules = [
        'data'   => 'required',
        'titulo' => 'required',
        'capa'   => 'required|image'
    ];

    private $image_config = [
        'width'  => 218,
        'height' => 290,
        'path'   => 'assets/img/clipping/capa/'
    ];

    public function index()
    {
        $clipping = Clipping::ordenados()->paginate(10);

        return $this->view('painel.clipping.index', compact('clipping'));
    }

    public function create()
    {
        return $this->view('painel.clipping.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['capa'] = CropImage::make('capa', $this->image_config);
            Clipping::create($input);
            Session::flash('sucesso', 'Projeto criado com sucesso.');

            return Redirect::route('painel.clipping.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $clipping = Clipping::findOrFail($id);

        return $this->view('painel.clipping.edit', compact('clipping'));
    }

    public function update($id)
    {
        $clipping = Clipping::findOrFail($id);
        $input    = Input::all();

        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            $clipping->update($input);
            Session::flash('sucesso', 'Projeto alterado com sucesso.');

            return Redirect::route('painel.clipping.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Clipping::destroy($id);
            Session::flash('sucesso', 'Projeto removido com sucesso.');

            return Redirect::route('painel.clipping.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover projeto.']);

        }
    }

}

laravel/app/views/painel/clipping/imagens/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="well form-group">
    {{ Form::label('imagem', 'Imagem') }}
    {{ Form::file('imagem', ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.clipping.imagens.index', $clipping->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/clipping/imagens/create.blade.php
@section('content')

    <legend>
        <h2><small>Clipping / Adicionar Imagem ao Projeto:</small> {{ $clipping->titulo }}</h2>
    </legend>

    {{ Form::open(['route' => ['painel.clipping.imagens.store', $clipping->id], 'files' => true]) }}

        @include('painel.clipping.imagens._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/clipping/imagens/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <a href="{{ route('painel.clipping.index') }}" title="Voltar para Clipping" class="btn btn-default">&larr; Voltar para Clipping</a>

    <legend>
        <h2>
            <small>Clipping / Imagens do Projeto:</small> {{ $clipping->titulo }}
            <a href="{{ URL::route('painel.clipping.imagens.create', $clipping->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Imagem</a>
        </h2>
    </legend>

    @if(count($imagens))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="clipping_imagens">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($imagens as $imagem)

                <tr class="tr-row" id="id_{{ $imagem->id }}">
                    <td>
                        <a href="#" class="btn btn-info btn-sm btn-move">
                            <span class="glyphicon glyphicon-move"></span>
                        </a>
                    </td>
                    <td><img src="{{ url('assets/img/clipping/'.$imagem->imagem) }}" alt="" style="width:100%;max-width:200px;height:auto;"></td>
                    <td class="crud-actions">
                       {{ Form::open(array('route' => array('painel.clipping.imagens.destroy', $clipping->id, $imagem->id), 'method' => 'delete')) }}
                        <input type="hidden" name="clipping_id" value="{{ $clipping->id }}">
                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                       {{ Form::close() }}
                    </td>
                </tr>

            @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma imagem cadastrada.</div>
    @endif

</div>

@stop